import Head from "next/head";
import React from "react";

interface Props {
  text: string;
}

function MetaData({ text }: Props) {
  return (
    <Head>
      <title>Grerëzat - {text}</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/images/grerzat.png" />
    </Head>
  );
}

export default MetaData;
