import Head from "next/head";
import { Box } from "@mui/material";
import { useAuth } from "@/context/AuthContext";
import Layout from "@/components/Layout";
import Text from "@/components/HomePage/Text";

export default function Home() {
  const { user } = useAuth();
  return (
    <>
      <Head>
        <title>Grerëzat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/grerzat.png" />
      </Head>
      <Layout>
        <Box
          sx={{
            display: "flex",
            flexDirection: "column",
            justifyContent: "center",
            alignItems: "flex-start",
            height: "100vh",
            backgroundColor: "#FFF6F6",
            gap: "50px",
            paddingLeft: "70px",
          }}
        >
          <Box
            sx={{
              display: {
                xs: "flex",
                md: "none",
                width: "100px",
              },
            }}
          >
            <img
              src="/images/grerzat.png"
              style={{ width: "100%", borderRadius: "50%" }}
            ></img>
          </Box>
          <Box sx={{ width: "50%" }}>
            <Text />
          </Box>
        </Box>
      </Layout>
    </>
  );
}
